In [2]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print a
print " "
print np.reshape(a,(2,-1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
 
[[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [60]:
a = {'a':1,'b':2}

In [62]:
for name in a:
    print name

a
b


In [16]:
a = np.random.rand(2,3,4)
a.prod()

1.3438117072454992e-12

In [17]:
a.shape[1:]

(3, 4)

In [18]:
np.prod(a.shape[1:])

12

In [19]:
np.zeros([1,10])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [37]:
a = np.random.rand(1000)
print max(a), min(a)

0.999501437368 0.00437156257631


In [43]:
'W' + str(1)

'W1'

In [44]:
np.random.rand(2,3)

array([[ 0.55458916,  0.47846853,  0.21433458],
       [ 0.69256609,  0.49647821,  0.45277525]])

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
range(1,10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
a = (1,3,2)
b = (3,4,2)
c = [a]
c.append(b)
c

[(1, 3, 2), (3, 4, 2)]

In [59]:
range(9,-1,-1)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [70]:
min_val = 1e-6
max_val = 1e-1
vals_temp = np.random.rand(10)
vals = min_val + ((vals_temp-min(vals_temp))*(max_val-min_val))/(max(vals_temp)-min(vals_temp))
print vals_temp
print vals

[ 0.69000152  0.84067577  0.10400165  0.10540073  0.01525539  0.536347
  0.81620076  0.8601594   0.20953259  0.52526983]
[  7.98608865e-02   9.76940062e-02   1.05046039e-02   1.06701926e-02
   1.00000000e-06   6.16750357e-02   9.47972550e-02   1.00000000e-01
   2.29947662e-02   6.03639917e-02]


In [76]:
np.log(.05)
10**np.log10(0.025)


0.025000000000000005

In [79]:
num_points = 5
learning_rate = 10**np.random.uniform(-6, -1,num_points)
weight_rate = 10**np.random.uniform(np.log10(.009), np.log10(.05),num_points)
print learning_rate
print weight_rate

[  3.03367379e-04   2.56548052e-04   9.13706893e-02   5.06991526e-03
   5.00583082e-05]
[ 0.03447138  0.0357242   0.01769358  0.01614854  0.03760397]


In [92]:
weight_rate = 10**np.random.uniform(np.log10(.009), np.log10(.05),10000)
print min(weight_rate)
print max(weight_rate)

0.00900154645964
0.0499935372003


In [101]:
from timeit import default_timer as timer
print "start"
start = timer()
print np.sqrt(2.0/3072)
print "end"
end = timer()
print end-start

start
0.025515518154
end
0.000223159790039


In [104]:
a = np.array([[1,2,3],[4,5,6]])
print a

[[1 2 3]
 [4 5 6]]


In [108]:
mu_a = np.mean(a,axis = 0)
a-mu_a

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

In [109]:
np.sum(a,axis = 0)

array([5, 7, 9])

In [110]:
10**.5

3.1622776601683795

In [114]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [10]:
a = np.random.rand(2,4)
print a
b,c = a.shape
print b
print c
range(0,b)

[[ 0.25500984  0.41117325  0.35327425  0.89822056]
 [ 0.95775968  0.96490707  0.82781518  0.93678483]]
2
4


[0, 1]

In [13]:
a

array([[ 0.25500984,  0.41117325,  0.35327425,  0.89822056],
       [ 0.95775968,  0.96490707,  0.82781518,  0.93678483]])

In [21]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print a
p = 1
a[:,p:-p]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[2, 3, 4],
       [7, 8, 9]])

In [37]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [35]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
a = np.array([[[0,1,2],[10,11,12]]])
print a

[[[ 0  1  2]
  [10 11 12]]]


In [58]:
a.transpose(1,0,2)

array([[[ 0,  1,  2]],

       [[10, 11, 12]]])

In [44]:
a = np.array([[0,1,2],[3,4,5]])
print a

[[0 1 2]
 [3 4 5]]


In [46]:
a.transpose(1,0)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [61]:
a = np.ones([1,2,3,4])
print a.shape
print a.transpose(1,0,2,3).shape


(1, 2, 3, 4)
(2, 1, 3, 4)


In [74]:
a = np.round(np.random.rand(14)*20)
print a
print a[0:10:2]


[ 16.   8.  13.  10.   5.  11.   3.   5.   6.  12.  14.  12.  19.   7.]
[ 16.  13.   5.   3.   6.]


In [78]:
x = np.random.rand(4,4)
print x
x.flatten()[10] = 10
print x

[[ 0.31368864  0.96457572  0.62576955  0.09134992]
 [ 0.18372827  0.25455635  0.35413056  0.04937083]
 [ 0.9101775   0.30291213  0.69860328  0.65634354]
 [ 0.02726941  0.13160082  0.07559342  0.95584815]]
[[ 0.31368864  0.96457572  0.62576955  0.09134992]
 [ 0.18372827  0.25455635  0.35413056  0.04937083]
 [ 0.9101775   0.30291213  0.69860328  0.65634354]
 [ 0.02726941  0.13160082  0.07559342  0.95584815]]


In [86]:
a = (3,2,10)
np.prod(a)

60

In [88]:
rel_error()

NameError: name 'rel_error' is not defined

In [91]:
for layer in range(2):
    print layer
print layer

0
1
1


In [97]:
a = 3
b = 2
print range(a)
print range(a,a+b)

[0, 1, 2]
[3, 4]


In [105]:
nl = 5
a = 2
c = 2
print nl
for A in range(nl-1,nl-1-a,-1):
    print A
for C in range(A-1,0,-1):
    print C

5
4
3
2
1


In [110]:
param = {}
for layer in range(3):
    param['W'+ str(layer)] = np.array([layer,layer/10])
    param['b'+ str(layer)] = np.array([0])
print param
for layer, w in param.iteritems():
    if str(layer).startswith('W'):
        print w

{'W1': array([1, 0]), 'b0': array([0]), 'W2': array([2, 0]), 'b2': array([0]), 'W0': array([0, 0]), 'b1': array([0])}
[1 0]
[2 0]
[0 0]


In [14]:
import numpy as np
a = np.random.rand(10,2,1)
mask = np.random.choice(a.shape[0], 2)
print mask
print a
a[mask]

[8 4]
[[[ 0.66862174]
  [ 0.24057318]]

 [[ 0.64566707]
  [ 0.74664294]]

 [[ 0.86495037]
  [ 0.1462108 ]]

 [[ 0.25260407]
  [ 0.09053615]]

 [[ 0.59086689]
  [ 0.55078002]]

 [[ 0.12530605]
  [ 0.19794095]]

 [[ 0.3656875 ]
  [ 0.78399902]]

 [[ 0.52715654]
  [ 0.42290583]]

 [[ 0.06810992]
  [ 0.60797933]]

 [[ 0.55676904]
  [ 0.24585285]]]


array([[[ 0.06810992],
        [ 0.60797933]],

       [[ 0.59086689],
        [ 0.55078002]]])

In [15]:
print range(2)

[0, 1]


In [17]:
a = np.random.rand(4)
print a
b = np.copy(a)
b[0] = 1
print a
print b

[  5.94201247e-03   5.70756570e-05   6.74507955e-01   7.62377810e-01]
[  5.94201247e-03   5.70756570e-05   6.74507955e-01   7.62377810e-01]
[  1.00000000e+00   5.70756570e-05   6.74507955e-01   7.62377810e-01]


In [36]:
a = np.random.rand(500,10)
b = np.random.rand(10,200)

import time
numIter = 10000

t_start = time.time()
for ii in range(numIter):
    c = np.dot(a,b)
    d = np.dot(a,b)
    e = c+d

t_per_iter_sep = (time.time()-t_start)/numIter

a = np.random.rand(500,10)
b = np.random.rand(10,b.shape[1]*2)

t_start = time.time()
for ii in range(numIter):
    c = np.dot(a,b)

t_per_iter_com = (time.time()-t_start)/numIter

perFaster = (t_per_iter_sep-t_per_iter_com)/t_per_iter_sep*100

print t_per_iter_sep
print t_per_iter_com
print perFaster

0.000195420908928
0.000112979006767
42.1868379453


In [48]:
a = np.random.rand(500,10)
b = np.random.rand(10,200)

import time
numIter = 100

t_start = time.time()
for ii in range(numIter):
    c = np.dot(a,b)
    d = np.dot(a,b)
    e = c+d

t_per_iter_sep = (time.time()-t_start)/numIter

t_start = time.time()
for ii in range(numIter):
    c = np.dot(a,np.concatenate((b,b),axis = 1))

t_per_iter_com = (time.time()-t_start)/numIter

perFaster = (t_per_iter_sep-t_per_iter_com)/t_per_iter_sep*100

print t_per_iter_sep
print t_per_iter_com
print perFaster

0.000200510025024
0.00012964963913
35.3400713436


In [43]:
a = np.random.rand(3,2)
print a

b = np.concatenate((a,a))
print b

[[ 0.44058473  0.20330871]
 [ 0.51287846  0.37876293]
 [ 0.64226346  0.08871139]]
[[ 0.44058473  0.20330871]
 [ 0.51287846  0.37876293]
 [ 0.64226346  0.08871139]
 [ 0.44058473  0.20330871]
 [ 0.51287846  0.37876293]
 [ 0.64226346  0.08871139]]


In [4]:
import numpy as np
d = 10**np.random.rand(1000)

import matplotlib.pyplot as plt
plt.hist(d, 50)

(array([ 71.,  61.,  48.,  41.,  43.,  40.,  40.,  40.,  30.,  30.,  28.,
         31.,  22.,  25.,  16.,  21.,  21.,  23.,  19.,  15.,  12.,  18.,
          4.,  13.,  13.,  16.,  14.,  11.,  20.,  15.,   8.,  12.,  14.,
          9.,  13.,  12.,  16.,   7.,   6.,  13.,   9.,   9.,  10.,   7.,
          7.,   8.,   4.,  14.,  12.,   9.]),
 array([ 1.00217505,  1.18136724,  1.36055944,  1.53975164,  1.71894384,
         1.89813604,  2.07732824,  2.25652043,  2.43571263,  2.61490483,
         2.79409703,  2.97328923,  3.15248142,  3.33167362,  3.51086582,
         3.69005802,  3.86925022,  4.04844242,  4.22763461,  4.40682681,
         4.58601901,  4.76521121,  4.94440341,  5.12359561,  5.3027878 ,
         5.48198   ,  5.6611722 ,  5.8403644 ,  6.0195566 ,  6.19874879,
         6.37794099,  6.55713319,  6.73632539,  6.91551759,  7.09470979,
         7.27390198,  7.45309418,  7.63228638,  7.81147858,  7.99067078,
         8.16986298,  8.34905517,  8.52824737,  8.70743957,  8.88663177,
 

In [9]:
a = np.random.rand(2)
a.astype(np.int)


array([0, 0])