In [27]:
import numpy as np
numClass = 10
numTrain = 4
numFeature = 3
w = np.random.rand(numFeature,numClass)
x = np.random.rand(numTrain,numFeature)

In [34]:
scores = x.dot(w)
correct = np.round(np.random.rand(numTrain,1)*numClass-.5).astype(int)


In [51]:
print x.shape
x[0,None].T
print x.T.shape

(4, 3)
(3, 4)


In [132]:
a = np.array([[1,2],[4,5],[7,8],[10,11]])
b = np.array([[0],[1],[0],[0]])
c = np.array([1,1,0,1])
b.shape

(4, 1)

In [152]:
a[xrange(4),c]

array([ 2,  5,  7, 11])

In [154]:
np.zeros([3,2])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [163]:
np.sum(a,axis=1)

array([ 3,  9, 15, 21])

In [172]:
c = np.random.choice(10,2)
print c

[0 1]


In [174]:
np.argmax(a,axis = 0)

array([3, 3])

In [181]:
d = {(1,2):0.12,(1,3):0.13}
d = {d,(3,4):0.34}

SyntaxError: invalid syntax (<ipython-input-181-3ac68f81138b>, line 2)

In [187]:
10**.1

1.2589254117941673

In [199]:
np.log10(1e-6)

-6.0

In [198]:
10^-5

-15

In [214]:
x = np.random.rand(10,2)
print np.max(0,x)
x[-1,0]

TypeError: only length-1 arrays can be converted to Python scalars

In [212]:
print xrange(200)

xrange(200)


In [250]:
10**(1.5*np.random.randn(10))

array([  9.12247794e-02,   3.61341803e+00,   5.54231143e+00,
         1.02683547e+01,   1.33497823e-02,   2.65787306e+00,
         1.41612017e+01,   4.60696075e-02,   2.71786964e-03,
         7.47417234e-02])

In [252]:
10**np.random.uniform(-6,1,10)

array([  1.12522238e-02,   1.18118498e-05,   4.02994523e-04,
         1.24280758e+00,   7.73183860e-04,   1.75623350e-05,
         8.44361432e-06,   9.53218311e-05,   3.30446649e-01,
         2.22371110e-05])

In [256]:
np.random.randint(1,10,10)

array([9, 9, 1, 7, 3, 2, 7, 7, 7, 9])

In [266]:
a = np.random.rand(2,1)
b = np.random.rand(2,1)
c = np.random.rand(2,)
AA, BB, CC = np.meshgrid(a,b,c)
AA = AA.flatten()
AA

array([ 0.42964201,  0.42964201,  0.87896164,  0.87896164,  0.42964201,
        0.42964201,  0.87896164,  0.87896164])

In [267]:
num_hyper = 4 # number of hyper parameters to try
learning_rates = 10**np.random.uniform(-9,-3,num_hyper) 
regularizations = 10**np.random.uniform(-1.1,1.1,num_hyper) 
num_hiddens = np.random.randint(10,501,num_hyper) 
num_iter = 1000
batch_size = 200

lr, reg, hidden = np.meshgrid(learning_rates,regularizations,num_hiddens)
lr = lr.flatten()
reg = reg.flatten()
hidden = hidden.flatten()

In [268]:
hidden.shape

(64,)

In [293]:
np.log(10**.1)

0.23025850929940461

In [298]:
np.log(10**-3)

-6.9077552789821368

In [305]:
np.log(10**-1.5)


-3.4538776394910684

In [306]:
np.log(10**-1)

-2.3025850929940455